// Generated by CoffeeScript 1.4.0

/*
 Simple replace based templating language
 which works in Chrome packaged apps.

 Syntax : template is a string with {{ variables }}
          data is a hash of variables with values

 Example: Alagu.render("Hello {{ tester }}", {tester : 'Alagu'})
*/


(function() {
  var Alagu, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Alagu = {};

  root.Alagu = Alagu;

  Alagu.render = function(template, data) {
    var render_template, value, variable, variable_item, variable_items, variables_strings, _i, _j, _len, _len1;
    variables_strings = template.match(/{{((.*?))}}/gim);
    variable_items = [];
    for (_i = 0, _len = variables_strings.length; _i < _len; _i++) {
      variable = variables_strings[_i];
      variable_item = variable.replace("{{", "").replace("}}", "").trim();
      variable_items.push({
        name: variable_item,
        template: variable
      });
    }
    render_template = template;
    for (_j = 0, _len1 = variable_items.length; _j < _len1; _j++) {
      variable = variable_items[_j];
      if (data && data.hasOwnProperty(variable.name)) {
        value = data[variable.name];
      } else {
        value = "";
      }
      render_template = render_template.replace(variable.template, value);
    }
    return render_template;
  };

}).call(this);
